language: node_js
node_js:
- '6'
before_install:
- npm install -g typescript
- npm install -g typings
- npm install -g protractor
- typings install

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - 'webdriver-manager update --standalone --firefox'
  - sleep 3 # give xvfb some time to start
  - ionic serve
  - sleep 10
script:
- npm test